import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { TanStackRouterVite } from "@tanstack/router-plugin/vite";
import { VitePWA } from "vite-plugin-pwa";
import path from "node:path";

// https://vite.dev/config/
export default defineConfig({
  define: {
    // Build-time-baked commit, mirrors the Go binary's
    // internal/version.Commit. Used by the version-mismatch banner to
    // detect when the server has deployed a newer build than the
    // currently-loaded bundle.
    __BUILD_COMMIT__: JSON.stringify(process.env.VITE_BUILD_COMMIT ?? "dev"),
  },
  plugins: [
    TanStackRouterVite({
      routesDirectory: "./src/routes",
      generatedRouteTree: "./src/routeTree.gen.ts",
      autoCodeSplitting: true,
      // Non-route files in routes/ use the "-" prefix (tsr.config.json
      // routeFileIgnorePrefix). Example: -AdminLanding.tsx beside
      // admin/index.tsx.
    }),
    react(),
    tailwindcss(),
    // v1.8.0e: PWA support via vite-plugin-pwa. Generates the service
    // worker (sw.js) + manifest at build time. registerType "autoUpdate"
    // lets workbox roll a new SW + reload precached assets when the
    // operator deploys a fresh build. The generated SW uses workbox
    // defaults: precache static assets only, runtime caching is
    // intentionally NOT enabled for /api/* — auth-scoped responses
    // must not be cached cross-session.
    VitePWA({
      registerType: "autoUpdate",
      // The manifest is generated by the plugin into dist/manifest.webmanifest;
      // we keep the existing /site.webmanifest hand-written so older
      // installs don't break, but the plugin's manifest is authoritative
      // going forward.
      manifestFilename: "manifest.webmanifest",
      includeAssets: [
        "favicon.svg",
        "favicon.ico",
        "apple-touch-icon.png",
        "favicon-192.png",
        "favicon-512.png",
      ],
      manifest: {
        name: "Basement",
        short_name: "Basement",
        description: "Multi-backend storage control plane",
        start_url: "/",
        display: "standalone",
        theme_color: "#C9874B",
        background_color: "#F4ECDD",
        icons: [
          {
            src: "/android-chrome-192x192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "/android-chrome-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
          },
          {
            src: "/android-chrome-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        // Precache the built app shell (HTML + hashed JS/CSS + images).
        // We intentionally do NOT add runtimeCaching rules for /api/*:
        // those responses are auth-scoped and must always hit the
        // network so a logged-out user never sees a previous user's
        // data from cache. Default `navigateFallback` would serve
        // index.html for SPA route URLs; allow it but exclude /api/.
        globPatterns: ["**/*.{js,css,html,svg,png,ico,woff,woff2}"],
        navigateFallback: "index.html",
        navigateFallbackDenylist: [/^\/api\//],
      },
      devOptions: {
        // Don't generate a SW in `pnpm dev` — saves operator from
        // stale-cache surprises mid-cycle. The SW is built + tested
        // via `pnpm build` and `pnpm preview`.
        enabled: false,
      },
    }),
  ],
  resolve: {
    alias: { "@": path.resolve(__dirname, "./src") },
  },
  build: {
    outDir: "../internal/web/dist",
    emptyOutDir: true,
    assetsDir: "assets",
    sourcemap: true,
  },
  server: {
    proxy: {
      "/api": "http://localhost:8080",
    },
  },
});
