// v1.8.0e — manifest sanity check.
//
// The PWA manifest is generated by vite-plugin-pwa at build time, but
// the hand-written /site.webmanifest fallback lives in
// frontend/public/site.webmanifest for back-compat with already-
// installed PWAs that registered the older URL. This test asserts
// both:
//   1. site.webmanifest exists + carries the required fields the
//      "Add to Home Screen" prompt depends on (name, icons in 192 +
//      512, start_url, display, theme_color).
//   2. vite.config.ts wires VitePWA with the same fields so the
//      generated manifest.webmanifest matches.
//   3. index.html declares the iOS standalone meta tags.
//
// File contents are pulled via Vite's `?raw` query so the test
// doesn't need node:fs (the test runs in jsdom under app-tsconfig,
// which intentionally omits node types).

import { describe, it, expect } from "vitest";

// Vite/Vitest serve these as the file contents at runtime.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — virtual ?raw query, no .d.ts for these files
import manifestRaw from "../../public/site.webmanifest?raw";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import viteConfigRaw from "../../vite.config.ts?raw";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import indexHtmlRaw from "../../index.html?raw";

type ManifestIcon = {
  src: string;
  sizes: string;
  type?: string;
  purpose?: string;
};

type Manifest = {
  name?: string;
  short_name?: string;
  description?: string;
  start_url?: string;
  display?: string;
  theme_color?: string;
  background_color?: string;
  icons?: ManifestIcon[];
};

function readManifest(): Manifest {
  return JSON.parse(manifestRaw as string) as Manifest;
}

describe("PWA manifest (site.webmanifest)", () => {
  it("has the required identity fields", () => {
    const m = readManifest();
    expect(m.name).toBe("Basement");
    expect(m.short_name).toBe("Basement");
    expect(m.description).toBeTruthy();
    expect(m.start_url).toBe("/");
    expect(m.display).toBe("standalone");
  });

  it("carries brand theme + background colors", () => {
    const m = readManifest();
    expect(m.theme_color).toMatch(/^#[0-9A-Fa-f]{6}$/);
    expect(m.background_color).toMatch(/^#[0-9A-Fa-f]{6}$/);
  });

  it("includes 192px + 512px icons with a maskable variant", () => {
    const m = readManifest();
    expect(m.icons).toBeDefined();
    const icons = m.icons ?? [];
    expect(icons.some((i) => i.sizes === "192x192")).toBe(true);
    expect(icons.some((i) => i.sizes === "512x512")).toBe(true);
    expect(icons.some((i) => i.purpose?.includes("maskable"))).toBe(true);
  });
});

describe("PWA wiring in vite.config.ts", () => {
  it("registers vite-plugin-pwa with the same identity fields", () => {
    const vite = viteConfigRaw as string;
    expect(vite).toMatch(/VitePWA/);
    expect(vite).toMatch(/registerType:\s*"autoUpdate"/);
    expect(vite).toMatch(/manifestFilename:\s*"manifest\.webmanifest"/);
    // Critical: the SW must not cache /api/* responses (they're
    // auth-scoped). The denylist regex catches it before workbox's
    // navigateFallback serves index.html on API failures.
    expect(vite).toMatch(/navigateFallbackDenylist/);
    expect(vite).toMatch(/\/\^\\\/api\\\//);
  });
});

describe("HTML PWA meta tags", () => {
  it("declares the iOS standalone hints + manifest link", () => {
    const html = indexHtmlRaw as string;
    expect(html).toMatch(/<link\s+rel="manifest"/);
    expect(html).toMatch(
      /<meta\s+name="apple-mobile-web-app-capable"\s+content="yes"/,
    );
    expect(html).toMatch(
      /<meta\s+name="apple-mobile-web-app-status-bar-style"/,
    );
    expect(html).toMatch(/<link\s+rel="apple-touch-icon"/);
    expect(html).toMatch(/<meta\s+name="theme-color"/);
  });
});
