/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FilesIndexRouteImport } from "./routes/files/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as ShareTokenRouteImport } from "./routes/share/$token"
import { Route as FilesSyncsRouteImport } from "./routes/files/syncs"
import { Route as FilesSharesRouteImport } from "./routes/files/shares"
import { Route as FilesKeysRouteImport } from "./routes/files/keys"
import { Route as FilesCidRouteImport } from "./routes/files/$cid"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as AdminSystemRouteImport } from "./routes/admin/system"
import { Route as AdminPoliciesRouteImport } from "./routes/admin/policies"
import { Route as AdminLoginRouteImport } from "./routes/admin/login"
import { Route as FilesSyncsIndexRouteImport } from "./routes/files/syncs/index"
import { Route as FilesSharesIndexRouteImport } from "./routes/files/shares/index"
import { Route as FilesCidIndexRouteImport } from "./routes/files/$cid/index"
import { Route as AdminUsersIndexRouteImport } from "./routes/admin/users/index"
import { Route as AdminKeysIndexRouteImport } from "./routes/admin/keys/index"
import { Route as AdminClustersIndexRouteImport } from "./routes/admin/clusters/index"
import { Route as AdminBucketsIndexRouteImport } from "./routes/admin/buckets/index"
import { Route as FilesSyncsNewRouteImport } from "./routes/files/syncs/new"
import { Route as FilesSharesNewRouteImport } from "./routes/files/shares/new"
import { Route as FilesBucketsConnectRouteImport } from "./routes/files/buckets/connect"
import { Route as AdminUsersNewRouteImport } from "./routes/admin/users/new"
import { Route as AdminClustersNewRouteImport } from "./routes/admin/clusters/new"
import { Route as AdminClustersCidIndexRouteImport } from "./routes/admin/clusters/$cid/index"
import { Route as FilesCidBBidRouteImport } from "./routes/files/$cid/b/$bid"
import { Route as AdminClustersCidLayoutRouteImport } from "./routes/admin/clusters/$cid/layout"
import { Route as AdminClustersCidEditRouteImport } from "./routes/admin/clusters/$cid/edit"
import { Route as AdminClustersCidKeysIdRouteImport } from "./routes/admin/clusters/$cid/keys/$id"
import { Route as AdminClustersCidBucketsIdRouteImport } from "./routes/admin/clusters/$cid/buckets/$id"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: "/files/",
  path: "/files/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: "/share/$token",
  path: "/share/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSyncsRoute = FilesSyncsRouteImport.update({
  id: "/files/syncs",
  path: "/files/syncs",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSharesRoute = FilesSharesRouteImport.update({
  id: "/files/shares",
  path: "/files/shares",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesKeysRoute = FilesKeysRouteImport.update({
  id: "/files/keys",
  path: "/files/keys",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesCidRoute = FilesCidRouteImport.update({
  id: "/files/$cid",
  path: "/files/$cid",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: "/admin/system",
  path: "/admin/system",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: "/admin/policies",
  path: "/admin/policies",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/admin/login",
  path: "/admin/login",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSyncsIndexRoute = FilesSyncsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FilesSyncsRoute,
} as any)
const FilesSharesIndexRoute = FilesSharesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FilesSharesRoute,
} as any)
const FilesCidIndexRoute = FilesCidIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FilesCidRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminKeysIndexRoute = AdminKeysIndexRouteImport.update({
  id: "/admin/keys/",
  path: "/admin/keys/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersIndexRoute = AdminClustersIndexRouteImport.update({
  id: "/admin/clusters/",
  path: "/admin/clusters/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBucketsIndexRoute = AdminBucketsIndexRouteImport.update({
  id: "/admin/buckets/",
  path: "/admin/buckets/",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSyncsNewRoute = FilesSyncsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => FilesSyncsRoute,
} as any)
const FilesSharesNewRoute = FilesSharesNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => FilesSharesRoute,
} as any)
const FilesBucketsConnectRoute = FilesBucketsConnectRouteImport.update({
  id: "/files/buckets/connect",
  path: "/files/buckets/connect",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminClustersNewRoute = AdminClustersNewRouteImport.update({
  id: "/admin/clusters/new",
  path: "/admin/clusters/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersCidIndexRoute = AdminClustersCidIndexRouteImport.update({
  id: "/admin/clusters/$cid/",
  path: "/admin/clusters/$cid/",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesCidBBidRoute = FilesCidBBidRouteImport.update({
  id: "/b/$bid",
  path: "/b/$bid",
  getParentRoute: () => FilesCidRoute,
} as any)
const AdminClustersCidLayoutRoute = AdminClustersCidLayoutRouteImport.update({
  id: "/admin/clusters/$cid/layout",
  path: "/admin/clusters/$cid/layout",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersCidEditRoute = AdminClustersCidEditRouteImport.update({
  id: "/admin/clusters/$cid/edit",
  path: "/admin/clusters/$cid/edit",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersCidKeysIdRoute = AdminClustersCidKeysIdRouteImport.update({
  id: "/admin/clusters/$cid/keys/$id",
  path: "/admin/clusters/$cid/keys/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersCidBucketsIdRoute =
  AdminClustersCidBucketsIdRouteImport.update({
    id: "/admin/clusters/$cid/buckets/$id",
    path: "/admin/clusters/$cid/buckets/$id",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/policies": typeof AdminPoliciesRoute
  "/admin/system": typeof AdminSystemRoute
  "/admin/users": typeof AdminUsersRouteWithChildren
  "/files/$cid": typeof FilesCidRouteWithChildren
  "/files/keys": typeof FilesKeysRoute
  "/files/shares": typeof FilesSharesRouteWithChildren
  "/files/syncs": typeof FilesSyncsRouteWithChildren
  "/share/$token": typeof ShareTokenRoute
  "/admin/": typeof AdminIndexRoute
  "/files/": typeof FilesIndexRoute
  "/admin/clusters/new": typeof AdminClustersNewRoute
  "/admin/users/new": typeof AdminUsersNewRoute
  "/files/buckets/connect": typeof FilesBucketsConnectRoute
  "/files/shares/new": typeof FilesSharesNewRoute
  "/files/syncs/new": typeof FilesSyncsNewRoute
  "/admin/buckets/": typeof AdminBucketsIndexRoute
  "/admin/clusters/": typeof AdminClustersIndexRoute
  "/admin/keys/": typeof AdminKeysIndexRoute
  "/admin/users/": typeof AdminUsersIndexRoute
  "/files/$cid/": typeof FilesCidIndexRoute
  "/files/shares/": typeof FilesSharesIndexRoute
  "/files/syncs/": typeof FilesSyncsIndexRoute
  "/admin/clusters/$cid/edit": typeof AdminClustersCidEditRoute
  "/admin/clusters/$cid/layout": typeof AdminClustersCidLayoutRoute
  "/files/$cid/b/$bid": typeof FilesCidBBidRoute
  "/admin/clusters/$cid/": typeof AdminClustersCidIndexRoute
  "/admin/clusters/$cid/buckets/$id": typeof AdminClustersCidBucketsIdRoute
  "/admin/clusters/$cid/keys/$id": typeof AdminClustersCidKeysIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/policies": typeof AdminPoliciesRoute
  "/admin/system": typeof AdminSystemRoute
  "/files/keys": typeof FilesKeysRoute
  "/share/$token": typeof ShareTokenRoute
  "/admin": typeof AdminIndexRoute
  "/files": typeof FilesIndexRoute
  "/admin/clusters/new": typeof AdminClustersNewRoute
  "/admin/users/new": typeof AdminUsersNewRoute
  "/files/buckets/connect": typeof FilesBucketsConnectRoute
  "/files/shares/new": typeof FilesSharesNewRoute
  "/files/syncs/new": typeof FilesSyncsNewRoute
  "/admin/buckets": typeof AdminBucketsIndexRoute
  "/admin/clusters": typeof AdminClustersIndexRoute
  "/admin/keys": typeof AdminKeysIndexRoute
  "/admin/users": typeof AdminUsersIndexRoute
  "/files/$cid": typeof FilesCidIndexRoute
  "/files/shares": typeof FilesSharesIndexRoute
  "/files/syncs": typeof FilesSyncsIndexRoute
  "/admin/clusters/$cid/edit": typeof AdminClustersCidEditRoute
  "/admin/clusters/$cid/layout": typeof AdminClustersCidLayoutRoute
  "/files/$cid/b/$bid": typeof FilesCidBBidRoute
  "/admin/clusters/$cid": typeof AdminClustersCidIndexRoute
  "/admin/clusters/$cid/buckets/$id": typeof AdminClustersCidBucketsIdRoute
  "/admin/clusters/$cid/keys/$id": typeof AdminClustersCidKeysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/policies": typeof AdminPoliciesRoute
  "/admin/system": typeof AdminSystemRoute
  "/admin/users": typeof AdminUsersRouteWithChildren
  "/files/$cid": typeof FilesCidRouteWithChildren
  "/files/keys": typeof FilesKeysRoute
  "/files/shares": typeof FilesSharesRouteWithChildren
  "/files/syncs": typeof FilesSyncsRouteWithChildren
  "/share/$token": typeof ShareTokenRoute
  "/admin/": typeof AdminIndexRoute
  "/files/": typeof FilesIndexRoute
  "/admin/clusters/new": typeof AdminClustersNewRoute
  "/admin/users/new": typeof AdminUsersNewRoute
  "/files/buckets/connect": typeof FilesBucketsConnectRoute
  "/files/shares/new": typeof FilesSharesNewRoute
  "/files/syncs/new": typeof FilesSyncsNewRoute
  "/admin/buckets/": typeof AdminBucketsIndexRoute
  "/admin/clusters/": typeof AdminClustersIndexRoute
  "/admin/keys/": typeof AdminKeysIndexRoute
  "/admin/users/": typeof AdminUsersIndexRoute
  "/files/$cid/": typeof FilesCidIndexRoute
  "/files/shares/": typeof FilesSharesIndexRoute
  "/files/syncs/": typeof FilesSyncsIndexRoute
  "/admin/clusters/$cid/edit": typeof AdminClustersCidEditRoute
  "/admin/clusters/$cid/layout": typeof AdminClustersCidLayoutRoute
  "/files/$cid/b/$bid": typeof FilesCidBBidRoute
  "/admin/clusters/$cid/": typeof AdminClustersCidIndexRoute
  "/admin/clusters/$cid/buckets/$id": typeof AdminClustersCidBucketsIdRoute
  "/admin/clusters/$cid/keys/$id": typeof AdminClustersCidKeysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin/login"
    | "/admin/policies"
    | "/admin/system"
    | "/admin/users"
    | "/files/$cid"
    | "/files/keys"
    | "/files/shares"
    | "/files/syncs"
    | "/share/$token"
    | "/admin/"
    | "/files/"
    | "/admin/clusters/new"
    | "/admin/users/new"
    | "/files/buckets/connect"
    | "/files/shares/new"
    | "/files/syncs/new"
    | "/admin/buckets/"
    | "/admin/clusters/"
    | "/admin/keys/"
    | "/admin/users/"
    | "/files/$cid/"
    | "/files/shares/"
    | "/files/syncs/"
    | "/admin/clusters/$cid/edit"
    | "/admin/clusters/$cid/layout"
    | "/files/$cid/b/$bid"
    | "/admin/clusters/$cid/"
    | "/admin/clusters/$cid/buckets/$id"
    | "/admin/clusters/$cid/keys/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin/login"
    | "/admin/policies"
    | "/admin/system"
    | "/files/keys"
    | "/share/$token"
    | "/admin"
    | "/files"
    | "/admin/clusters/new"
    | "/admin/users/new"
    | "/files/buckets/connect"
    | "/files/shares/new"
    | "/files/syncs/new"
    | "/admin/buckets"
    | "/admin/clusters"
    | "/admin/keys"
    | "/admin/users"
    | "/files/$cid"
    | "/files/shares"
    | "/files/syncs"
    | "/admin/clusters/$cid/edit"
    | "/admin/clusters/$cid/layout"
    | "/files/$cid/b/$bid"
    | "/admin/clusters/$cid"
    | "/admin/clusters/$cid/buckets/$id"
    | "/admin/clusters/$cid/keys/$id"
  id:
    | "__root__"
    | "/"
    | "/admin/login"
    | "/admin/policies"
    | "/admin/system"
    | "/admin/users"
    | "/files/$cid"
    | "/files/keys"
    | "/files/shares"
    | "/files/syncs"
    | "/share/$token"
    | "/admin/"
    | "/files/"
    | "/admin/clusters/new"
    | "/admin/users/new"
    | "/files/buckets/connect"
    | "/files/shares/new"
    | "/files/syncs/new"
    | "/admin/buckets/"
    | "/admin/clusters/"
    | "/admin/keys/"
    | "/admin/users/"
    | "/files/$cid/"
    | "/files/shares/"
    | "/files/syncs/"
    | "/admin/clusters/$cid/edit"
    | "/admin/clusters/$cid/layout"
    | "/files/$cid/b/$bid"
    | "/admin/clusters/$cid/"
    | "/admin/clusters/$cid/buckets/$id"
    | "/admin/clusters/$cid/keys/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  FilesCidRoute: typeof FilesCidRouteWithChildren
  FilesKeysRoute: typeof FilesKeysRoute
  FilesSharesRoute: typeof FilesSharesRouteWithChildren
  FilesSyncsRoute: typeof FilesSyncsRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  AdminClustersNewRoute: typeof AdminClustersNewRoute
  FilesBucketsConnectRoute: typeof FilesBucketsConnectRoute
  AdminBucketsIndexRoute: typeof AdminBucketsIndexRoute
  AdminClustersIndexRoute: typeof AdminClustersIndexRoute
  AdminKeysIndexRoute: typeof AdminKeysIndexRoute
  AdminClustersCidEditRoute: typeof AdminClustersCidEditRoute
  AdminClustersCidLayoutRoute: typeof AdminClustersCidLayoutRoute
  AdminClustersCidIndexRoute: typeof AdminClustersCidIndexRoute
  AdminClustersCidBucketsIdRoute: typeof AdminClustersCidBucketsIdRoute
  AdminClustersCidKeysIdRoute: typeof AdminClustersCidKeysIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/": {
      id: "/files/"
      path: "/files"
      fullPath: "/files/"
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/admin"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/share/$token": {
      id: "/share/$token"
      path: "/share/$token"
      fullPath: "/share/$token"
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/syncs": {
      id: "/files/syncs"
      path: "/files/syncs"
      fullPath: "/files/syncs"
      preLoaderRoute: typeof FilesSyncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/shares": {
      id: "/files/shares"
      path: "/files/shares"
      fullPath: "/files/shares"
      preLoaderRoute: typeof FilesSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/keys": {
      id: "/files/keys"
      path: "/files/keys"
      fullPath: "/files/keys"
      preLoaderRoute: typeof FilesKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/$cid": {
      id: "/files/$cid"
      path: "/files/$cid"
      fullPath: "/files/$cid"
      preLoaderRoute: typeof FilesCidRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/admin/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/system": {
      id: "/admin/system"
      path: "/admin/system"
      fullPath: "/admin/system"
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/policies": {
      id: "/admin/policies"
      path: "/admin/policies"
      fullPath: "/admin/policies"
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/login": {
      id: "/admin/login"
      path: "/admin/login"
      fullPath: "/admin/login"
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/syncs/": {
      id: "/files/syncs/"
      path: "/"
      fullPath: "/files/syncs/"
      preLoaderRoute: typeof FilesSyncsIndexRouteImport
      parentRoute: typeof FilesSyncsRoute
    }
    "/files/shares/": {
      id: "/files/shares/"
      path: "/"
      fullPath: "/files/shares/"
      preLoaderRoute: typeof FilesSharesIndexRouteImport
      parentRoute: typeof FilesSharesRoute
    }
    "/files/$cid/": {
      id: "/files/$cid/"
      path: "/"
      fullPath: "/files/$cid/"
      preLoaderRoute: typeof FilesCidIndexRouteImport
      parentRoute: typeof FilesCidRoute
    }
    "/admin/users/": {
      id: "/admin/users/"
      path: "/"
      fullPath: "/admin/users/"
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    "/admin/keys/": {
      id: "/admin/keys/"
      path: "/admin/keys"
      fullPath: "/admin/keys/"
      preLoaderRoute: typeof AdminKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/": {
      id: "/admin/clusters/"
      path: "/admin/clusters"
      fullPath: "/admin/clusters/"
      preLoaderRoute: typeof AdminClustersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/buckets/": {
      id: "/admin/buckets/"
      path: "/admin/buckets"
      fullPath: "/admin/buckets/"
      preLoaderRoute: typeof AdminBucketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/syncs/new": {
      id: "/files/syncs/new"
      path: "/new"
      fullPath: "/files/syncs/new"
      preLoaderRoute: typeof FilesSyncsNewRouteImport
      parentRoute: typeof FilesSyncsRoute
    }
    "/files/shares/new": {
      id: "/files/shares/new"
      path: "/new"
      fullPath: "/files/shares/new"
      preLoaderRoute: typeof FilesSharesNewRouteImport
      parentRoute: typeof FilesSharesRoute
    }
    "/files/buckets/connect": {
      id: "/files/buckets/connect"
      path: "/files/buckets/connect"
      fullPath: "/files/buckets/connect"
      preLoaderRoute: typeof FilesBucketsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/users/new": {
      id: "/admin/users/new"
      path: "/new"
      fullPath: "/admin/users/new"
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    "/admin/clusters/new": {
      id: "/admin/clusters/new"
      path: "/admin/clusters/new"
      fullPath: "/admin/clusters/new"
      preLoaderRoute: typeof AdminClustersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/$cid/": {
      id: "/admin/clusters/$cid/"
      path: "/admin/clusters/$cid"
      fullPath: "/admin/clusters/$cid/"
      preLoaderRoute: typeof AdminClustersCidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/$cid/b/$bid": {
      id: "/files/$cid/b/$bid"
      path: "/b/$bid"
      fullPath: "/files/$cid/b/$bid"
      preLoaderRoute: typeof FilesCidBBidRouteImport
      parentRoute: typeof FilesCidRoute
    }
    "/admin/clusters/$cid/layout": {
      id: "/admin/clusters/$cid/layout"
      path: "/admin/clusters/$cid/layout"
      fullPath: "/admin/clusters/$cid/layout"
      preLoaderRoute: typeof AdminClustersCidLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/$cid/edit": {
      id: "/admin/clusters/$cid/edit"
      path: "/admin/clusters/$cid/edit"
      fullPath: "/admin/clusters/$cid/edit"
      preLoaderRoute: typeof AdminClustersCidEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/$cid/keys/$id": {
      id: "/admin/clusters/$cid/keys/$id"
      path: "/admin/clusters/$cid/keys/$id"
      fullPath: "/admin/clusters/$cid/keys/$id"
      preLoaderRoute: typeof AdminClustersCidKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/$cid/buckets/$id": {
      id: "/admin/clusters/$cid/buckets/$id"
      path: "/admin/clusters/$cid/buckets/$id"
      fullPath: "/admin/clusters/$cid/buckets/$id"
      preLoaderRoute: typeof AdminClustersCidBucketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface FilesCidRouteChildren {
  FilesCidIndexRoute: typeof FilesCidIndexRoute
  FilesCidBBidRoute: typeof FilesCidBBidRoute
}

const FilesCidRouteChildren: FilesCidRouteChildren = {
  FilesCidIndexRoute: FilesCidIndexRoute,
  FilesCidBBidRoute: FilesCidBBidRoute,
}

const FilesCidRouteWithChildren = FilesCidRoute._addFileChildren(
  FilesCidRouteChildren,
)

interface FilesSharesRouteChildren {
  FilesSharesNewRoute: typeof FilesSharesNewRoute
  FilesSharesIndexRoute: typeof FilesSharesIndexRoute
}

const FilesSharesRouteChildren: FilesSharesRouteChildren = {
  FilesSharesNewRoute: FilesSharesNewRoute,
  FilesSharesIndexRoute: FilesSharesIndexRoute,
}

const FilesSharesRouteWithChildren = FilesSharesRoute._addFileChildren(
  FilesSharesRouteChildren,
)

interface FilesSyncsRouteChildren {
  FilesSyncsNewRoute: typeof FilesSyncsNewRoute
  FilesSyncsIndexRoute: typeof FilesSyncsIndexRoute
}

const FilesSyncsRouteChildren: FilesSyncsRouteChildren = {
  FilesSyncsNewRoute: FilesSyncsNewRoute,
  FilesSyncsIndexRoute: FilesSyncsIndexRoute,
}

const FilesSyncsRouteWithChildren = FilesSyncsRoute._addFileChildren(
  FilesSyncsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  FilesCidRoute: FilesCidRouteWithChildren,
  FilesKeysRoute: FilesKeysRoute,
  FilesSharesRoute: FilesSharesRouteWithChildren,
  FilesSyncsRoute: FilesSyncsRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  AdminClustersNewRoute: AdminClustersNewRoute,
  FilesBucketsConnectRoute: FilesBucketsConnectRoute,
  AdminBucketsIndexRoute: AdminBucketsIndexRoute,
  AdminClustersIndexRoute: AdminClustersIndexRoute,
  AdminKeysIndexRoute: AdminKeysIndexRoute,
  AdminClustersCidEditRoute: AdminClustersCidEditRoute,
  AdminClustersCidLayoutRoute: AdminClustersCidLayoutRoute,
  AdminClustersCidIndexRoute: AdminClustersCidIndexRoute,
  AdminClustersCidBucketsIdRoute: AdminClustersCidBucketsIdRoute,
  AdminClustersCidKeysIdRoute: AdminClustersCidKeysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
