/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FilesIndexRouteImport } from "./routes/files/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as FilesSharesRouteImport } from "./routes/files/shares"
import { Route as FilesKeysRouteImport } from "./routes/files/keys"
import { Route as FilesCidRouteImport } from "./routes/files/$cid"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as AdminSystemRouteImport } from "./routes/admin/system"
import { Route as AdminLoginRouteImport } from "./routes/admin/login"
import { Route as AdminKeysIndexRouteImport } from "./routes/admin/keys/index"
import { Route as AdminClustersIndexRouteImport } from "./routes/admin/clusters/index"
import { Route as AdminBucketsIndexRouteImport } from "./routes/admin/buckets/index"
import { Route as FilesClustersNewRouteImport } from "./routes/files/clusters/new"
import { Route as AdminClustersCidIndexRouteImport } from "./routes/admin/clusters/$cid/index"
import { Route as FilesCidBBidRouteImport } from "./routes/files/$cid/b/$bid"
import { Route as AdminClustersCidLayoutRouteImport } from "./routes/admin/clusters/$cid/layout"
import { Route as AdminClustersCidKeysIdRouteImport } from "./routes/admin/clusters/$cid/keys/$id"
import { Route as AdminClustersCidBucketsIdRouteImport } from "./routes/admin/clusters/$cid/buckets/$id"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: "/files/",
  path: "/files/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSharesRoute = FilesSharesRouteImport.update({
  id: "/files/shares",
  path: "/files/shares",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesKeysRoute = FilesKeysRouteImport.update({
  id: "/files/keys",
  path: "/files/keys",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesCidRoute = FilesCidRouteImport.update({
  id: "/files/$cid",
  path: "/files/$cid",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: "/admin/system",
  path: "/admin/system",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/admin/login",
  path: "/admin/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKeysIndexRoute = AdminKeysIndexRouteImport.update({
  id: "/admin/keys/",
  path: "/admin/keys/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersIndexRoute = AdminClustersIndexRouteImport.update({
  id: "/admin/clusters/",
  path: "/admin/clusters/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBucketsIndexRoute = AdminBucketsIndexRouteImport.update({
  id: "/admin/buckets/",
  path: "/admin/buckets/",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesClustersNewRoute = FilesClustersNewRouteImport.update({
  id: "/files/clusters/new",
  path: "/files/clusters/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersCidIndexRoute = AdminClustersCidIndexRouteImport.update({
  id: "/admin/clusters/$cid/",
  path: "/admin/clusters/$cid/",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesCidBBidRoute = FilesCidBBidRouteImport.update({
  id: "/b/$bid",
  path: "/b/$bid",
  getParentRoute: () => FilesCidRoute,
} as any)
const AdminClustersCidLayoutRoute = AdminClustersCidLayoutRouteImport.update({
  id: "/admin/clusters/$cid/layout",
  path: "/admin/clusters/$cid/layout",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersCidKeysIdRoute = AdminClustersCidKeysIdRouteImport.update({
  id: "/admin/clusters/$cid/keys/$id",
  path: "/admin/clusters/$cid/keys/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClustersCidBucketsIdRoute =
  AdminClustersCidBucketsIdRouteImport.update({
    id: "/admin/clusters/$cid/buckets/$id",
    path: "/admin/clusters/$cid/buckets/$id",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/system": typeof AdminSystemRoute
  "/admin/users": typeof AdminUsersRoute
  "/files/$cid": typeof FilesCidRouteWithChildren
  "/files/keys": typeof FilesKeysRoute
  "/files/shares": typeof FilesSharesRoute
  "/admin/": typeof AdminIndexRoute
  "/files/": typeof FilesIndexRoute
  "/files/clusters/new": typeof FilesClustersNewRoute
  "/admin/buckets/": typeof AdminBucketsIndexRoute
  "/admin/clusters/": typeof AdminClustersIndexRoute
  "/admin/keys/": typeof AdminKeysIndexRoute
  "/admin/clusters/$cid/layout": typeof AdminClustersCidLayoutRoute
  "/files/$cid/b/$bid": typeof FilesCidBBidRoute
  "/admin/clusters/$cid/": typeof AdminClustersCidIndexRoute
  "/admin/clusters/$cid/buckets/$id": typeof AdminClustersCidBucketsIdRoute
  "/admin/clusters/$cid/keys/$id": typeof AdminClustersCidKeysIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/system": typeof AdminSystemRoute
  "/admin/users": typeof AdminUsersRoute
  "/files/$cid": typeof FilesCidRouteWithChildren
  "/files/keys": typeof FilesKeysRoute
  "/files/shares": typeof FilesSharesRoute
  "/admin": typeof AdminIndexRoute
  "/files": typeof FilesIndexRoute
  "/files/clusters/new": typeof FilesClustersNewRoute
  "/admin/buckets": typeof AdminBucketsIndexRoute
  "/admin/clusters": typeof AdminClustersIndexRoute
  "/admin/keys": typeof AdminKeysIndexRoute
  "/admin/clusters/$cid/layout": typeof AdminClustersCidLayoutRoute
  "/files/$cid/b/$bid": typeof FilesCidBBidRoute
  "/admin/clusters/$cid": typeof AdminClustersCidIndexRoute
  "/admin/clusters/$cid/buckets/$id": typeof AdminClustersCidBucketsIdRoute
  "/admin/clusters/$cid/keys/$id": typeof AdminClustersCidKeysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/system": typeof AdminSystemRoute
  "/admin/users": typeof AdminUsersRoute
  "/files/$cid": typeof FilesCidRouteWithChildren
  "/files/keys": typeof FilesKeysRoute
  "/files/shares": typeof FilesSharesRoute
  "/admin/": typeof AdminIndexRoute
  "/files/": typeof FilesIndexRoute
  "/files/clusters/new": typeof FilesClustersNewRoute
  "/admin/buckets/": typeof AdminBucketsIndexRoute
  "/admin/clusters/": typeof AdminClustersIndexRoute
  "/admin/keys/": typeof AdminKeysIndexRoute
  "/admin/clusters/$cid/layout": typeof AdminClustersCidLayoutRoute
  "/files/$cid/b/$bid": typeof FilesCidBBidRoute
  "/admin/clusters/$cid/": typeof AdminClustersCidIndexRoute
  "/admin/clusters/$cid/buckets/$id": typeof AdminClustersCidBucketsIdRoute
  "/admin/clusters/$cid/keys/$id": typeof AdminClustersCidKeysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin/login"
    | "/admin/system"
    | "/admin/users"
    | "/files/$cid"
    | "/files/keys"
    | "/files/shares"
    | "/admin/"
    | "/files/"
    | "/files/clusters/new"
    | "/admin/buckets/"
    | "/admin/clusters/"
    | "/admin/keys/"
    | "/admin/clusters/$cid/layout"
    | "/files/$cid/b/$bid"
    | "/admin/clusters/$cid/"
    | "/admin/clusters/$cid/buckets/$id"
    | "/admin/clusters/$cid/keys/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin/login"
    | "/admin/system"
    | "/admin/users"
    | "/files/$cid"
    | "/files/keys"
    | "/files/shares"
    | "/admin"
    | "/files"
    | "/files/clusters/new"
    | "/admin/buckets"
    | "/admin/clusters"
    | "/admin/keys"
    | "/admin/clusters/$cid/layout"
    | "/files/$cid/b/$bid"
    | "/admin/clusters/$cid"
    | "/admin/clusters/$cid/buckets/$id"
    | "/admin/clusters/$cid/keys/$id"
  id:
    | "__root__"
    | "/"
    | "/admin/login"
    | "/admin/system"
    | "/admin/users"
    | "/files/$cid"
    | "/files/keys"
    | "/files/shares"
    | "/admin/"
    | "/files/"
    | "/files/clusters/new"
    | "/admin/buckets/"
    | "/admin/clusters/"
    | "/admin/keys/"
    | "/admin/clusters/$cid/layout"
    | "/files/$cid/b/$bid"
    | "/admin/clusters/$cid/"
    | "/admin/clusters/$cid/buckets/$id"
    | "/admin/clusters/$cid/keys/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  FilesCidRoute: typeof FilesCidRouteWithChildren
  FilesKeysRoute: typeof FilesKeysRoute
  FilesSharesRoute: typeof FilesSharesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  FilesClustersNewRoute: typeof FilesClustersNewRoute
  AdminBucketsIndexRoute: typeof AdminBucketsIndexRoute
  AdminClustersIndexRoute: typeof AdminClustersIndexRoute
  AdminKeysIndexRoute: typeof AdminKeysIndexRoute
  AdminClustersCidLayoutRoute: typeof AdminClustersCidLayoutRoute
  AdminClustersCidIndexRoute: typeof AdminClustersCidIndexRoute
  AdminClustersCidBucketsIdRoute: typeof AdminClustersCidBucketsIdRoute
  AdminClustersCidKeysIdRoute: typeof AdminClustersCidKeysIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/": {
      id: "/files/"
      path: "/files"
      fullPath: "/files/"
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/admin"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/shares": {
      id: "/files/shares"
      path: "/files/shares"
      fullPath: "/files/shares"
      preLoaderRoute: typeof FilesSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/keys": {
      id: "/files/keys"
      path: "/files/keys"
      fullPath: "/files/keys"
      preLoaderRoute: typeof FilesKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/$cid": {
      id: "/files/$cid"
      path: "/files/$cid"
      fullPath: "/files/$cid"
      preLoaderRoute: typeof FilesCidRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/admin/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/system": {
      id: "/admin/system"
      path: "/admin/system"
      fullPath: "/admin/system"
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/login": {
      id: "/admin/login"
      path: "/admin/login"
      fullPath: "/admin/login"
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/keys/": {
      id: "/admin/keys/"
      path: "/admin/keys"
      fullPath: "/admin/keys/"
      preLoaderRoute: typeof AdminKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/": {
      id: "/admin/clusters/"
      path: "/admin/clusters"
      fullPath: "/admin/clusters/"
      preLoaderRoute: typeof AdminClustersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/buckets/": {
      id: "/admin/buckets/"
      path: "/admin/buckets"
      fullPath: "/admin/buckets/"
      preLoaderRoute: typeof AdminBucketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/clusters/new": {
      id: "/files/clusters/new"
      path: "/files/clusters/new"
      fullPath: "/files/clusters/new"
      preLoaderRoute: typeof FilesClustersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/$cid/": {
      id: "/admin/clusters/$cid/"
      path: "/admin/clusters/$cid"
      fullPath: "/admin/clusters/$cid/"
      preLoaderRoute: typeof AdminClustersCidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/$cid/b/$bid": {
      id: "/files/$cid/b/$bid"
      path: "/b/$bid"
      fullPath: "/files/$cid/b/$bid"
      preLoaderRoute: typeof FilesCidBBidRouteImport
      parentRoute: typeof FilesCidRoute
    }
    "/admin/clusters/$cid/layout": {
      id: "/admin/clusters/$cid/layout"
      path: "/admin/clusters/$cid/layout"
      fullPath: "/admin/clusters/$cid/layout"
      preLoaderRoute: typeof AdminClustersCidLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/$cid/keys/$id": {
      id: "/admin/clusters/$cid/keys/$id"
      path: "/admin/clusters/$cid/keys/$id"
      fullPath: "/admin/clusters/$cid/keys/$id"
      preLoaderRoute: typeof AdminClustersCidKeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/clusters/$cid/buckets/$id": {
      id: "/admin/clusters/$cid/buckets/$id"
      path: "/admin/clusters/$cid/buckets/$id"
      fullPath: "/admin/clusters/$cid/buckets/$id"
      preLoaderRoute: typeof AdminClustersCidBucketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilesCidRouteChildren {
  FilesCidBBidRoute: typeof FilesCidBBidRoute
}

const FilesCidRouteChildren: FilesCidRouteChildren = {
  FilesCidBBidRoute: FilesCidBBidRoute,
}

const FilesCidRouteWithChildren = FilesCidRoute._addFileChildren(
  FilesCidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  FilesCidRoute: FilesCidRouteWithChildren,
  FilesKeysRoute: FilesKeysRoute,
  FilesSharesRoute: FilesSharesRoute,
  AdminIndexRoute: AdminIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  FilesClustersNewRoute: FilesClustersNewRoute,
  AdminBucketsIndexRoute: AdminBucketsIndexRoute,
  AdminClustersIndexRoute: AdminClustersIndexRoute,
  AdminKeysIndexRoute: AdminKeysIndexRoute,
  AdminClustersCidLayoutRoute: AdminClustersCidLayoutRoute,
  AdminClustersCidIndexRoute: AdminClustersCidIndexRoute,
  AdminClustersCidBucketsIdRoute: AdminClustersCidBucketsIdRoute,
  AdminClustersCidKeysIdRoute: AdminClustersCidKeysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
