#!/usr/bin/env bash
# basement — 5-minute installer
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/MattJackson/basement/main/scripts/install.sh | bash
#
# Or for review-before-run (recommended):
#   curl -sSLo install.sh https://raw.githubusercontent.com/MattJackson/basement/main/scripts/install.sh
#   less install.sh
#   bash install.sh
#
# What it does:
#   1. Verifies Docker is installed and the daemon is reachable.
#   2. Pulls ghcr.io/mattjackson/basement:latest.
#   3. Writes a minimal docker-compose.yml to ./basement/ (or
#      /opt/basement/ if invoked as root and ./ isn't writable).
#   4. Starts the container; basement auto-bootstraps a JWT secret +
#      initial admin password on first boot (see v1.11.0c).
#   5. Tails container logs until "Listening on" appears, then prints
#      the INITIAL ADMIN PASSWORD line basement emitted on stdout.
#
# Hard constraints:
#   - bash + POSIX coreutils only; no jq/yq/python dependency.
#   - Idempotent: rerunning over an existing install pulls + restarts
#     without overwriting the data volume or the on-disk secrets, so
#     the admin password the operator saw on first boot still works.
#   - Exits non-zero on any failure with a message naming what to fix.

set -euo pipefail

readonly IMAGE="ghcr.io/mattjackson/basement:latest"
readonly CONTAINER="basement"
readonly COMPOSE_BASENAME="docker-compose.yml"
readonly DEFAULT_PORT="8080"

# Pick an install directory the current user can write to. Prefer the
# CWD so the operator finds the compose file alongside whatever shell
# they're sitting in; fall back to /opt/basement when running as root.
pick_install_dir() {
  local cwd
  cwd="$(pwd)/basement"
  if mkdir -p "$cwd" 2>/dev/null; then
    echo "$cwd"
    return 0
  fi
  if [ "$(id -u)" = "0" ]; then
    mkdir -p /opt/basement
    echo "/opt/basement"
    return 0
  fi
  echo "install: cannot create a writable directory; rerun from a writable cwd or with sudo" >&2
  exit 1
}

# Detect docker compose vs legacy docker-compose. Outputs the command
# to invoke (one or two words).
detect_compose() {
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
    return 0
  fi
  if command -v docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
    return 0
  fi
  echo "install: docker compose (or docker-compose) is required; install Docker Desktop or the docker-compose-plugin package" >&2
  exit 1
}

require_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "install: docker is not in PATH; install Docker Engine (https://docs.docker.com/engine/install/) or Docker Desktop and rerun" >&2
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "install: docker daemon is not reachable; start Docker (or run with sudo if your user isn't in the docker group)" >&2
    exit 1
  fi
}

write_compose() {
  local dir="$1"
  local file="$dir/$COMPOSE_BASENAME"
  if [ -f "$file" ]; then
    echo "install: existing $file detected — leaving it in place; pulling + restarting" >&2
    return 0
  fi
  cat >"$file" <<EOF
# basement — minimal install (generated by scripts/install.sh)
#
# Auto-bootstrap is on: no env vars are required. On first boot
# basement generates a JWT signing secret + a random admin password
# and persists both under the basement-data volume. The password is
# also printed to stdout — see "docker logs basement | grep 'INITIAL
# ADMIN PASSWORD'" or rerun this installer.
#
# For production:
#   - Set BASEMENT_JWT_SECRET (base64-encoded, >= 32 bytes raw) so a
#     fresh volume keeps the same signing key across rebuilds.
#   - Set BASEMENT_ADMIN_PASSWORD_HASH (bcrypt) so the password isn't
#     persisted in plaintext at /var/lib/basement/.initial-admin-password.
#   - Put basement behind a TLS-terminating reverse proxy (Caddy /
#     Traefik / nginx) and set BASEMENT_PUBLIC_URL to its external URL.
services:
  basement:
    image: $IMAGE
    container_name: $CONTAINER
    restart: unless-stopped
    ports:
      - "${DEFAULT_PORT}:8080"
    volumes:
      - basement-data:/var/lib/basement
    # No environment block on purpose — bootstrap fills in JWT_SECRET
    # + ADMIN_PASSWORD on first boot.

volumes:
  basement-data:
EOF
  echo "install: wrote $file"
}

wait_for_listening() {
  local timeout="${1:-60}"
  local deadline=$(( $(date +%s) + timeout ))
  while [ "$(date +%s)" -lt "$deadline" ]; do
    if docker logs "$CONTAINER" 2>&1 | grep -q "listening\|Listening"; then
      return 0
    fi
    sleep 1
  done
  echo "install: timed out waiting for basement to log a Listening line; check 'docker logs $CONTAINER'" >&2
  return 1
}

extract_initial_password() {
  # Grep for the exact INITIAL ADMIN PASSWORD line emitted by the
  # bootstrap path. Returns the password (everything after the colon),
  # or empty when an explicit BASEMENT_ADMIN_PASSWORD(_HASH) was set.
  docker logs "$CONTAINER" 2>&1 | grep -m1 "^INITIAL ADMIN PASSWORD:" | sed 's/^INITIAL ADMIN PASSWORD: //'
}

main() {
  echo "basement installer — 5-minute install"

  require_docker
  local compose
  compose=$(detect_compose)
  echo "install: using compose command: $compose"

  local dir
  dir=$(pick_install_dir)
  echo "install: install directory: $dir"

  write_compose "$dir"

  echo "install: pulling $IMAGE"
  (cd "$dir" && $compose pull)

  echo "install: starting container"
  (cd "$dir" && $compose up -d)

  wait_for_listening 90 || exit 1

  local pw
  pw=$(extract_initial_password)

  echo
  echo "------------------------------------------------------------"
  echo "basement is running at http://localhost:$DEFAULT_PORT"
  if [ -n "$pw" ]; then
    echo "Initial admin user:     admin"
    echo "Initial admin password: $pw"
    echo "(Change it via /admin/users after first login.)"
  else
    echo "No auto-generated password in logs — looks like you already"
    echo "set BASEMENT_ADMIN_PASSWORD or BASEMENT_ADMIN_PASSWORD_HASH"
    echo "explicitly. Log in with the username + password you supplied."
  fi
  echo "------------------------------------------------------------"
  echo
  echo "Compose file: $dir/$COMPOSE_BASENAME"
  echo "Stop:         (cd $dir && $compose down)"
  echo "Logs:         docker logs -f $CONTAINER"
}

main "$@"
